import { lazy } from 'react';
import { Routes } from '@/shared/constants';
import { IRoute, RolesDict } from '@/shared/types';

export const routes: IRoute[] = [
  {
    id: 0,
    path: '/',
    component: lazy(() => import('../ui/auth')),
    isPublic: true,
    roles: [RolesDict.APPLICANT, RolesDict.EMPLOYEE, RolesDict.STUDENT],
    withLayout: false,
  },
  {
    id: 1,
    path: Routes.MAIN,
    component: lazy(() => import('../ui/main')),
    isPublic: false,
    roles: [RolesDict.APPLICANT, RolesDict.EMPLOYEE, RolesDict.STUDENT],
    withLayout: true,
  },
  {
    id: 2,
    path: Routes.EMPLOYEE,
    component: lazy(() => import('../ui/employee')),
    isPublic: false,
    roles: [RolesDict.APPLICANT, RolesDict.EMPLOYEE, RolesDict.STUDENT],
    withLayout: true,
  },
  {
    id: 3,
    path: Routes.STUDENT,
    component: lazy(() => import('../ui/student')),
    isPublic: false,
    roles: [RolesDict.STUDENT],
    withLayout: true,
  },
  {
    id: 4,
    path: Routes.APPLICANT,
    component: lazy(() => import('../ui/applicant')),
    isPublic: false,
    roles: [RolesDict.APPLICANT],
    withLayout: true,
  },
  // {
  //   id: 5,
  //   path: Routes.EMPLOYMENT_CONTRACT,
  //   component: lazy(() => import('../ui/TRASH/employment-contract')),
  //   isPublic: false,
  //   roles: [RolesDict.EMPLOYEE],
  //   withLayout: true,
  // },
  // {
  //   id: 6,
  //   path: Routes.INTERNAL_ADMISSION,
  //   component: lazy(() => import('../ui/TRASH/internal-admission')),
  //   isPublic: false,
  //   roles: [RolesDict.EMPLOYEE],
  //   withLayout: true,
  // },
  // {
  //   id: 7,
  //   path: Routes.TRANSFER,
  //   component: lazy(() => import('../ui/TRASH/transfer')),
  //   isPublic: false,
  //   roles: [RolesDict.EMPLOYEE],
  //   withLayout: true,
  // },
  // {
  //   id: 8,
  //   path: Routes.VACATION,
  //   component: lazy(() => import('../ui/TRASH/vacation')),
  //   isPublic: false,
  //   roles: [RolesDict.EMPLOYEE],
  //   withLayout: true,
  // },
  // {
  //   id: 9,
  //   path: Routes.REQUESTS,
  //   component: lazy(() => import('../ui/type-of-requests')),
  //   isPublic: false,
  //   roles: [RolesDict.APPLICANT, RolesDict.EMPLOYEE, RolesDict.STUDENT],
  //   withLayout: false,
  // },
];
